import pandas as pd
import seaborn
import matplotlib.pyplot as plt

# Loading the data
data = pd.read_csv(filepath_or_buffer="/PATH/TO/YOUR/DATA.csv", dtype="str")

# Cleaning up the time-stamp
data = data.replace({"t": r"t"}, {"t": ""}, regex=True)
data = data.replace({"t": r"h"}, {"t": ""}, regex=True)

# Casting the columns in the format we desire
data["do590"] = data["do590"].astype(float)
data["t"] = data["t"].astype(int)
data["well"] = data["well"].astype("category")

# Ordering the wells in the desired fashion
data["well"] = data["well"].cat.reorder_categories(
    [
        "A1",
        "A2",
        "A3",
        "A4",
        "A5",
        "A6",
        "A7",
        "A8",
        "A9",
        "A10",
        "A11",
        "A12",
        "B1",
        "B2",
        "B3",
        "B4",
        "B5",
        "B6",
        "B7",
        "B8",
        "B9",
        "B10",
        "B11",
        "B12",
        "C1",
        "C2",
        "C3",
        "C4",
        "C5",
        "C6",
        "C7",
        "C8",
        "C9",
        "C10",
        "C11",
        "C12",
        "D1",
        "D2",
        "D3",
        "D4",
        "D5",
        "D6",
        "D7",
        "D8",
        "D9",
        "D10",
        "D11",
        "D12",
        "E1",
        "E2",
        "E3",
        "E4",
        "E5",
        "E6",
        "E7",
        "E8",
        "E9",
        "E10",
        "E11",
        "E12",
        "F1",
        "F2",
        "F3",
        "F4",
        "F5",
        "F6",
        "F7",
        "F8",
        "F9",
        "F10",
        "F11",
        "F12",
        "G1",
        "G2",
        "G3",
        "G4",
        "G5",
        "G6",
        "G7",
        "G8",
        "G9",
        "G10",
        "G11",
        "G12",
        "H1",
        "H2",
        "H3",
        "H4",
        "H5",
        "H6",
        "H7",
        "H8",
        "H9",
        "H10",
        "H11",
        "H12",
    ],
    ordered=True,
)

# The name of the wells are renamed according to the Phenotype MicroArray plate analyzed/visualized
# This list must have the same length as the one above
data["well"] = data["well"].cat.rename_categories(
    [
        "A1 - Negative Control",
        "A2 - L-Arabinose",
        "A3 - N-Acetyl-D-Glucosamine",
        "A4 - D-Saccharic Acid",
        "A5 - Succinic Acid",
        "A6 - D-Galactose",
        "A7 - L-Aspartic Acid",
        "A8 - L-Proline",
        "A9 - D-Alanine",
        "A10 - D-Trehalose",
        "A11 - D-Mannose",
        "A12 - Dulcitol",
        "B1 - D-Serine",
        "B2 - D-Sorbitol",
        "B3 - Glycerol",
        "B4 - L-Fucose",
        "B5 - D-Glucuronic Acid",
        "B6 - D-Gluconic Acid",
        "B7 - D,L-α-Glycerol- Phosphate",
        "B8 - D-Xylose",
        "B9 - L-Lactic Acid",
        "B10 - Formic Acid",
        "B11 - D-Mannitol",
        "B12 - L-Glutamic Acid",
        "C1 - D-Glucose-6- Phosphate",
        "C2 - D-Galactonic Acid-γ-Lactone",
        "C3 - D,L-Malic Acid",
        "C4 - D-Ribose",
        "C5 - Tween 20",
        "C6 - L-Rhamnose",
        "C7 - D-Fructose",
        "C8 - Acetic Acid",
        "C9 - α-D-Glucose",
        "C10 - Maltose",
        "C11 - D-Melibiose",
        "C12 - Thymidine",
        "D1 - L-Asparagine",
        "D2 - D-Aspartic Acid",
        "D3 - D-Glucosaminic Acid",
        "D4 - 1,2-Propanediol",
        "D5 - Tween 40",
        "D6 - α-Keto-Glutaric Acid",
        "D7 - α-Keto-Butyric Acid",
        "D8 - α-Methyl-D- Galactoside",
        "D9 - α-D-Lactose",
        "D10 - Lactulose",
        "D11 - Sucrose",
        "D12 - Uridine",
        "E1 - L-Glutamine",
        "E2 - m-Tartaric Acid",
        "E3 - D-Glucose-1- Phosphate",
        "E4 - D-Fructose-6- Phosphate",
        "E5 - Tween 80",
        "E6 - α-Hydroxy Glutaric Acid-γ- Lactone",
        "E7 - α-Hydroxy Butyric Acid",
        "E8 - ß-Methyl-D- Glucoside",
        "E9 - Adonitol",
        "E10 - Maltotriose",
        "E11 - 2-Deoxy Adenosine",
        "E12 - Adenosine",
        "F1 - Glycyl-L-Aspartic Acid",
        "F2 - Citric Acid",
        "F3 - m-Inositol",
        "F4 - D-Threonine",
        "F5 - Fumaric Acid",
        "F6 - Bromo Succinic Acid",
        "F7 - Propionic Acid",
        "F8 - Mucic Acid",
        "F9 - Glycolic Acid",
        "F10 - Glyoxylic Acid",
        "F11 - D-Cellobiose",
        "F12 - Inosine",
        "G1 - Glycyl-L- Glutamic Acid",
        "G2 - Tricarballylic Acid",
        "G3 - L-Serine",
        "G4 - L-Threonine",
        "G5 - L-Alanine",
        "G6 - L-Alanyl-Glycine",
        "G7 - Acetoacetic Acid",
        "G8 - N-Acetyl-ß-D- Mannosamine",
        "G9 - Mono Methyl Succinate",
        "G10 - Methyl Pyruvate",
        "G11 - D-Malic Acid",
        "G12 - L-Malic Acid",
        "H1 - Glycyl-L-Proline",
        "H2 - p-Hydroxy Phenyl Acetic Acid",
        "H3 - m-Hydroxy Phenyl Acetic Acid",
        "H4 - Tyramine",
        "H5 - D-Psicose",
        "H6 - L-Lyxose",
        "H7 - Glucuronamide",
        "H8 - Pyruvic Acid",
        "H9 - L-Galactonic Acid-γ-Lactone",
        "H10 - D-Galacturonic Acid",
        "H11 - Phenylethyl- amine",
        "H12 - -Aminoethanol",
    ]
)

# Removing unwanted wells
data = data[
    ~data["well"].isin(
        [
            "A2 - L-Arabinose",
            "A4 - D-Saccharic Acid",
            "A5 - Succinic Acid",
            "A7 - L-Aspartic Acid",
            "A8 - L-Proline",
            "A9 - D-Alanine",
            "A11 - D-Mannose",
            "A12 - Dulcitol",
            "B1 - D-Serine",
            "B2 - D-Sorbitol",
            "B4 - L-Fucose",
            "B5 - D-Glucuronic Acid",
            "B6 - D-Gluconic Acid",
            "B7 - D,L-α-Glycerol- Phosphate",
            "B8 - D-Xylose",
            "B9 - L-Lactic Acid",
            "B10 - Formic Acid",
            "B12 - L-Glutamic Acid",
            "C1 - D-Glucose-6- Phosphate",
            "C2 - D-Galactonic Acid-γ-Lactone",
            "C3 - D,L-Malic Acid",
            "C5 - Tween 20",
            "C6 - L-Rhamnose",
            "C8 - Acetic Acid",
            "C11 - D-Melibiose",
            "C12 - Thymidine",
            "D1 - L-Asparagine",
            "D2 - D-Aspartic Acid",
            "D3 - D-Glucosaminic Acid",
            "D4 - 1,2-Propanediol",
            "D5 - Tween 40",
            "D6 - α-Keto-Glutaric Acid",
            "D7 - α-Keto-Butyric Acid",
            "D8 - α-Methyl-D- Galactoside",
            "D9 - α-D-Lactose",
            "D10 - Lactulose",
            "D11 - Sucrose",
            "D12 - Uridine",
            "E1 - L-Glutamine",
            "E2 - m-Tartaric Acid",
            "E3 - D-Glucose-1- Phosphate",
            "E4 - D-Fructose-6- Phosphate",
            "E5 - Tween 80",
            "E6 - α-Hydroxy Glutaric Acid-γ- Lactone",
            "E7 - α-Hydroxy Butyric Acid",
            "E9 - Adonitol",
            "E11 - 2-Deoxy Adenosine",
            "E12 - Adenosine",
            "F1 - Glycyl-L-Aspartic Acid",
            "F2 - Citric Acid",
            "F4 - D-Threonine",
            "F5 - Fumaric Acid",
            "F6 - Bromo Succinic Acid",
            "F7 - Propionic Acid",
            "F8 - Mucic Acid",
            "F9 - Glycolic Acid",
            "F10 - Glyoxylic Acid",
            "F11 - D-Cellobiose",
            "F12 - Inosine",
            "G1 - Glycyl-L- Glutamic Acid",
            "G2 - Tricarballylic Acid",
            "G3 - L-Serine",
            "G4 - L-Threonine",
            "G5 - L-Alanine",
            "G6 - L-Alanyl-Glycine",
            "G7 - Acetoacetic Acid",
            "G8 - N-Acetyl-ß-D- Mannosamine",
            "G9 - Mono Methyl Succinate",
            "G10 - Methyl Pyruvate",
            "G11 - D-Malic Acid",
            "G12 - L-Malic Acid",
            "H1 - Glycyl-L-Proline",
            "H2 - p-Hydroxy Phenyl Acetic Acid",
            "H3 - m-Hydroxy Phenyl Acetic Acid",
            "H4 - Tyramine",
            "H5 - D-Psicose",
            "H6 - L-Lyxose",
            "H7 - Glucuronamide",
            "H8 - Pyruvic Acid",
            "H9 - L-Galactonic Acid-γ-Lactone",
            "H10 - D-Galacturonic Acid",
            "H11 - Phenylethyl- amine",
            "H12 - -Aminoethanol",
        ]
    )
]

# Renaming the columns for visualization
data = data.rename(columns={"t": "Time (h)", "well": "Well", "do590": "OD590"})

# Preparing the data for seaborn
data = data.pivot("Well", "Time (h)", "OD590")

# Creating the figure at the desired size
plt.figure(figsize=(5.2, 4.5))

seaborn.heatmap(
    data,
    linewidths=0.25,
    square=True,
    cmap="viridis_r",
    vmin=0,
    vmax=3,
    cbar_kws={"label": "OD590"},
)
plt.title("PM1", fontsize=15)
plt.tight_layout()
plt.savefig(fname="C2.2_MP1_2_FINAL.png", dpi=150)
